### ISSUE TITLE
Import data from Google Sheets document

### ISSUE THREAD

**Issue by calda** [gtgreekweek/Greek-Week-Calendar#2]
We want to back this page by a Google Sheet so the data can be input by non-technical members of exec (or perhaps the events committee). Go ahead and make a new spreadsheet with the following information:
 - Event name
 - Time and date
 - Location
 - Tags (e.g. indoor event, outdoor event, water event, deadline, etc.)
 - Short description (1-2 sentences)
 - Has Rule Book content? *(We'll want a field that controls whether or not there is a "View Rules" button, so we don't bother trying to link them to the rule book for something like "Committee Applications Due")*

You can set up the spreadsheet to be available as a `csv` under `File > Publish to Web...`. 

The standings site uses a library called [`Tabletop`](https://github.com/jsoma/tabletop) to load information from the Standing spreadsheet. This was due to cross-origin policy issues, so it's probably a good idea to use that here too. *([example from greek-week-standings](https://github.com/gtgreekweek/Greek-Week-Standings/blob/b0f6906e6846c7e2b95b3291c04b2c6cf7fd2f3d/chapter.js#L8))*

**Comment by calda** [comment]
for next week: #3

**Comment by ChangedNameTo** [comment]
I've started on the tags for the events, so far I have the page looking like this: 
![image](https://user-images.githubusercontent.com/9056294/37067075-31aaee0e-2176-11e8-9028-677d4005d936.png)

I have a data array called tags that I'll be iterating over. What I need is a list of tags you think are necessary so that I can add them to the style sheet so that the tags can have multiple colors, be filtered, etc. 

I've gone ahead and pushed my changes, just let me know so I can get to styling.

@calda / @dbecker1

**Comment by dbecker1** [comment]
Closed that on accident - added initial commit of the event loading in b76e24db7ae5e0fbc1717b1c499a514297e60a16

**Comment by calda** [comment]
dope @dbecker1
